# Day 2

In [1]:
import numpy as np
import torch

### View (Reshape)

numpy 에서는 .reshape()를 쓴다.

In [2]:
t = np.array([[[0,1,2],
               [3,4,5]],
               
               [[6,7,8],
                [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [4]:
print(ft.view(-1,3)) # -1의 의미: 앞은 모르겠고, 일단 두 번째 차원은 3개의 element를 가질래
print(ft.view([-1,3]).shape) # (2*2,3) = (4,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
print(ft.view([-1,1,3])) # 첫 번째 차원은 모르겠고, 마지막 2개 차원을 (1,3)으로 맞춰줘
print(ft.view([-1,1,3]).shape) # (2*2*,1,3) = (4,1,3)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [7]:
a = np.zeros((2,3,4,5))
print(a)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


python 은 표기 방식이 matlab과 다르다.<br>
큰 덩어리부터 제시되고, 마지막 2개가 matrix 형태로 제시된다.<br>
따라서 (2,3,4,5) 텐서가 있다면 마지막 (4,5) 함수가 3덩어리 있고, 그 덩어리가 2개 있는 형태로 만들어지는 것이다.

### Squeeze

In [8]:
ft = torch.FloatTensor([[0],
                        [1],
                        [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [9]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [16]:
a = np.zeros((2,3,1,5))
aa = torch.FloatTensor(a)

print(aa)
print(aa.squeeze())
print(aa.squeeze().shape)

print(aa.squeeze(dim=2))
print(aa.squeeze(dim=-1).shape) # 1이 있는 차원이 아니면 딱히 변하지 않는다..

tensor([[[[0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.]]]])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.Size([2, 3, 5])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.Size([2, 3, 1, 5])


### Unsqueeze
내가 원하는 dimension에 1을 넣어준다.
이 때는 내가 원하는 dimension을 꼭 명시해 줄 필요가 있다.

In [17]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [18]:
print(ft.unsqueeze(0)) # dim = 0 과 같음, 따라서 dim 0에 1을 넣어라. 라는 뜻
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [23]:
print(ft.view(1,-1)) # 더이상 ft에서의 차원과 다르다. 차원이 하나 들어났다는 것을 확인할 것.
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [20]:
print(ft.unsqueeze(1)) # dim = 1 과 같음, 따라서 dim 1에 1을 넣어라. 라는 뜻
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [21]:
print(ft.unsqueeze(-1)) # 마지막 dimension. 즉 dim=1과 같음
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [24]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [25]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [26]:
# masking 등으로 사용될 수 있다. 
bt = torch.ByteTensor([True, False, False, True]) # boolean 값 저장
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [27]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [28]:
bt = (lt == 3)
print(bt)

tensor([False, False,  True, False])


### Concatenate

In [29]:
x = torch.FloatTensor([[1,2], 
                       [3,4]])
y = torch.FloatTensor([[5,6],
                       [7,8]])

In [30]:
print(torch.cat([x,y], dim = 0)) # 행이 커지도록 붙이기
print(torch.cat([x,y], dim = 1)) # 열이 커지도록 붙이기

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
concatinating을 편리하게 단축시켜 놓은 방법

In [31]:
# shape: (2,)
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [32]:
print(torch.stack([x,y,z])) # x, y, z 리스크를 쌓아라 -> (3,2)
print(torch.stack([x,y,z], dim = 1)) # dimension 1에 대하여 쌓아라 -> (2,3)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [33]:
# 위와 같은 결과를 다르게 표시하는 방법
# x.unsqueeze(0) 의 차원(1,2
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros

In [34]:
x = torch.FloatTensor([[0,1,2],
                       [2,1,0]])
print(x.shape)
print(x)

torch.Size([2, 3])
tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [35]:
# 같은 device(cpu, gpu 0, gpu 1...)에 선언해 주어야 한다.
print(torch.ones_like(x)) # x 와 같은 사이즈의, 1로만 가득찬 텐서 returen
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [36]:
x = torch.FloatTensor([[1,2],
                       [3,4]])

In [37]:
print(x.mul(2.))
print(x)
print(x.mul_(2.)) # 새롭게 메모리에 텐서를 할당하지 않고도 연산을 수행할 수 있게 해줌.
print(x) # 그러나 garbage collector가 잘 작동하기 때문에 연산 속도는 크게 차이나지 않을 수 있음

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
