# Day 1

In [3]:
import numpy as np
import torch
import torch.nn as nn

In [4]:
t = np.array([0., 1.,2., 3., 4., 5., 6.])
print (t)

[0. 1. 2. 3. 4. 5. 6.]


### NOTE
array 안에 '.'을 찍는 이유
: float 형태로 저장한다는 뜻. .을 안찍으면 int 형태임

In [ ]:
print('Rank of t : ', t.ndim) # vector이다
print('Shape of t : ', t.shape) # 7개의 element가 담겨있다.

Rank of t :  1
Shape of t :  (7,)


: 

In [ ]:
print('t[0] t[1] t[-1]= ', t[0],t[1],t[-1]) # element
print('t[2:5] t[4:-1] = ', t[2:5], t[3:-1]) # Slicing
print('t[:2] t[3:]    = ', t[:2], t[3:])    # Slicing

t[0] t[1] t[-1]=  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [3. 4. 5.]
t[:2] t[3:]    =  [0. 1.] [3. 4. 5. 6.]


: 

Python의 index: 2:5는 0, 1, 2번째부터 4번째까지를 의미!! 헷갈리지 말아야 한다
-1번째는 matlab의 end와 동일

## 2D array with NumPy

In [ ]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


: 

In [ ]:
print('Rank of t : ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t :  2
Shape of t:  (4, 3)


: 

shape는 실제 차원 숫자 그래도 나온다. rank는 matrix의 경우 2로 출력된다.

## 1D array with PyTorch

In [ ]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


: 

|데이터 형식	|의미	|자료형	|CPU 텐서	|GPU 텐서|
|------|---|---|---|---|
|Byte	|부호 없는 8 비트 정수	|torch.uint8	|torch.ByteTensor	|torch.cuda.ByteTensor|
|Short	|부호 있는 16 비트 정수	|torch.short	|torch.ShortTensor	|torch.cuda.ShortTensor|
|Int	|부호 있는 32 비트 정수	|torch.int	|torch.IntTensor	|torch.cuda.IntTensor|
|Long	|부호 있는 64 비트 정수	|torch.long	|torch.LongTensor	|torch.cuda.LongTensor|
|Binary16	|16 비트 부동 소수점	|torch.half	torch.HalfTensor	|torch.cuda.HalfTensor|
|Brain Floating Point	|16 비트 부동 소수점	|torch.bfloat16	|torch.BFloat16Tensor	|torch.cuda.BFloat16Tensor|
|Float	|32 비트 부동 소수점	|torch.float	|torch.FloatTensor	|torch.cuda.FloatTensor|
|Double	|32 비트 부동 소수점	|torch.double	|torch.DoubleTensor	|torch.cuda.DoubleTensor|
|Boolean	|논리 형식	|torch.bool	|torch.BoolTensor	|torch.cuda.BoolTensor|
|Int8	|부호 있는 8 비트 정수	|torch.int8	|torch.CharTensor	|torch.CharTensor|
|Int16	|부호 있는 16 비트 정수	|torch.int16	|torch.ShortTensor	|torch.cuda.ShortTensor|
|Int32	|부호 있는 32 비트 정수	|torch.int32	|torch.IntTensor	|torch.cuda.IntTensor|
|Int64	|부호 있는 64 비트 정수	|torch.int64	|torch.LongTensor	|torch.cuda.LongTensor|
|Float16	|16 비트 부동 소수점	|torch.float16	|torch.HalfTensor	|torch.cuda.HalfTensor|
|Float32	|32 비트 부동 소수점	|torch.float32	|torch.FloatTensor	|torch.cuda.FloatTens|
|Float64	|64 비트 부동 소수점	|torch.float64	|torch.DoubleTensor	|torch.cuda.DoubleTensor|
|Complex32	|32 비트 복합 형식	|torch.complex32	 |	 |
|Complex64	|64 비트 복합 형식	|torch.complex64	 |	 |
|Complex128	|128 비트 복합 형식	|torch.complex128	 |	 |
|Complex128	|128 비트 복합 형식	|torch.cdouble	 	| |
|Quantized Int	|양자화된 부호 있는 4비트 정수	|torch.quint4x2	|torch.ByteTensor|	 |
|Quantized Int	|양자화된 부호 없는 8 비트 정수	|torch.quint8	|torch.ByteTensor|	 |
|Quantized Int	|양자화된 부호 있는 8 비트 정수	|torch.qint8	|torch.CharTensor|	 |
|Quantized Int	|양자화된 부호 있는 32 비트 정수	|torch.qfint32	|torch.IntTensor|	| 

PyTorch에서 지원하는 텐서의 유형은 위와 같습니다.
그 중, IntTensor, LongTensor, FloatTensor가 가장 많이 활용됩니다.
또한, torch.Tensor의 기본 유형은 torch.FloatTensor(torch.float32)를 따릅니다.

In [ ]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # element
print(t[2:5], t[4:-1]) # Slicing
print(t[:2], t[3:]) # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


: 

## 2D array with Pytorch

In [ ]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12]])
print(t)

print(t.dim()) # rank
print(t.shape) # Shape
print(t.size()) # Shape
print(t[:,1]) # 모든 차원 : 1번째 차원 값을 print
print(t[:,1].size()) # 모든 차원 : 1번째 차원 값의 크기 print
print(t[:, :-1]) # 모든 행, -1을 제외한 차원 값 print

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


: 

## Broadcasting
덧셈과 뺄셈을 할 때는 tensor의 크기가 같아야 한다.<br>
행렬곱을 수행할 때 마지막 차원과 첫번째 차원이 일치해야 한다.<br>
그러나 불가피하게 다른 크기의 행렬을 더하거나 빼는 사칙연산을 수행하여야 할 때가 있다.<br>
이때를 위하여 pytorch에서 제공하는 broadcasting 기능을 이용한다.

In [ ]:
# Same shape
m1 = torch.FloatTensor([[3,3]]) # 2차원 (1,2)
mm1 = torch.FloatTensor([3,3]) # 1차원 list (2,)
mmm1 = torch.FloatTensor([[[3,3]]]) # 3차원 (1,1,2)
m2 = torch.FloatTensor([[2,2]])

z = [[3,3]]
z1 = torch.FloatTensor(z)

print(m1.dim())
print(mm1.dim())
print(mmm1.dim())

print(m1.shape)
print('mm1.shape: ', mm1.shape)
print(mmm1.shape)

print(m2.shape)

print(m1+m2)

2
1
3
torch.Size([1, 2])
mm1.shape:  torch.Size([2])
torch.Size([1, 1, 2])
torch.Size([1, 2])
tensor([[5., 5.]])


: 

In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])  # shape (1,2)
m2 = torch.FloatTensor([3])  # shape(1,) -> shape (1,2)
print(m1 + m2)  # broadcasting 결과: [[1,2]] + [[3,3]]
print((m1+m2).shape)

tensor([[4., 5.]])
torch.Size([1, 2])


: 

In [ ]:
# tensor 간의 연산도 가능하다.
# 2 X 1 vector + 1 x 2 vector
m1 = torch.FloatTensor([[1,2]]) # (1,2) -> (2,2)
m2 = torch.FloatTensor([[3],[4]]) # (2,1) -> (2,2)
print(m1 + m2) 

print((m1+m2).shape)

tensor([[4., 5.],
        [5., 6.]])
torch.Size([2, 2])


: 

$\begin{bmatrix}1&2 \end{bmatrix}$ 가 $\begin{bmatrix}1&2\\1&2\\ \end{bmatrix}$ 로, 
$\begin{bmatrix}3\\4\\ \end{bmatrix}$ 가 $\begin{bmatrix}3&3\\4&4\\ \end{bmatrix}$ 로 변환되어 <br>
<br>
$\begin{bmatrix}1&2\\1&2\\ \end{bmatrix}$ + $\begin{bmatrix}3&3\\4&4\\ \end{bmatrix}$ = $\begin{bmatrix}4&5\\5&6\\ \end{bmatrix}$ <br>

!! broadcasting은 자동으로 작성되기 때문에 사용 시 매우 주의해야 한다.

## Maltiplication vs. Matrix Multiplication

In [ ]:
print()
print('------------')
print('Mul vs Matmul')
print('------------')
m1 = torch.FloatTensor([[1,2],
                        [3,4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('Shape of Matrix 1(m1): ', m1.shape) # (2,2)
print('Shape of Matrix 2(m2): ', m2.shape) # (2,1)
print(m1*m2) # (2,2)

# 곱하기 비교
print('m1.mul(m2) = ', m1.mul(m2)) 
print('m1.matmul(m2) = ', m1.matmul(m2)) 


------------
Mul vs Matmul
------------
Shape of Matrix 1(m1):  torch.Size([2, 2])
Shape of Matrix 2(m2):  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
m1.mul(m2) =  tensor([[1., 2.],
        [6., 8.]])
m1.matmul(m2) =  tensor([[ 5.],
        [11.]])


: 

- .mul()

element-wise 곱 계산 방법은 다음과 같다. 이는 * 연산과 동일하다

$\begin{bmatrix}1&2\\3&4\\ \end{bmatrix}$ * $\begin{bmatrix}1&1\\2&2\\ \end{bmatrix}$ =
$\begin{bmatrix}1&2\\6&8\\ \end{bmatrix}$

- .matmul()  

inner products / dot products / 행렬곱 방법은 다음과 같다.

$\begin{bmatrix}1&2\\3&4\\ \end{bmatrix}$ * $\begin{bmatrix}1\\2\\ \end{bmatrix}$ =
$\begin{bmatrix}5\\11\\ \end{bmatrix}$

## Mean

In [ ]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


: 

In [ ]:
# Can't use mean() on ingegers
t = torch.LongTensor([1,2])

try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


: 

You can also use t.mean for higher rank tensors to get mean of all elements, or mean by particular dimension

In [ ]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


: 

우리가 원하는 차원에 대해서만 mean 을 계산할 수 있다.

In [ ]:
# dim 을 axis로 써주면(?) numpy와 똑같다.
print(t.mean())
print(t.mean(dim=0)) # dimension 0 을 없애겠어! 
print(t.mean(dim=1))
print(t.mean(dim=-1)) # 마지막 dimension을 없애겠어!

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


: 

함수 $\begin{bmatrix}1&2\\3&4\\ \end{bmatrix}$ 에서

print(t.mean(dim=0)) 의 경우 dimension 0 을 없애겠다는 뜻이므로 

어찌 됐든 $\begin{bmatrix} ?&? \end{bmatrix}$ , 즉 (1,2) 모양(벡터)이 나와야 하는것이다.

따라서 결과는 $\begin{bmatrix} 2&3 \end{bmatrix}$
<br>
<br>
<br>
같은 방법으로 print(t.mean(dim=1)) 의 경우 dimension 1 을 없애겠다는 뜻이므로 

결과는 $\begin{bmatrix} 1.5\\3.5 \end{bmatrix}$

그런데 이건 그냥 벡터이므로 

[1.5, 3.5] 로 표시된다



## Sum

In [ ]:
t = torch.FloatTensor([[1,2],
                       [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


: 

In [ ]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


: 

## Max and Argmax

In [ ]:
t = torch.FloatTensor([[1,2], 
                       [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


: 

The max operatior returns one value of if it is called without an argument

In [ ]:
print(t.max()) # Returns one value: max

tensor(4.)


: 

The <span style="color: #2D3748; background-color: #f6f8fa;"> max</span> operator returns 2 values when called with dimension specified. <br>
The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [ ]:
print(t.max(dim=0)) # 제일 큰 값이 있는 dimension 0 

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


: 

In [ ]:
print('Max: ', t.max(dim=0)[0])
print('Max: ', t.max(dim=1)[0]) # index[0]은 차원 1이 사라지는 나머지 차원에서 최댓값 성분을 불러오란 의미
print('Argmax: ', t.max(dim=0)[1]) # index [1] 은 index 값을 불러오란 의미
print('Argmax: ', t.max(dim=1)[1])

Max:  tensor([3., 4.])
Max:  tensor([2., 4.])
Argmax:  tensor([1, 1])
Argmax:  tensor([1, 1])


: 

In [ ]:
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

: 

In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


: 

In [ ]:
# 민수랑 간단한 예제 작성
minsu = nn.Sequential(
    nn.Conv2d(1,20,5),
    nn.ReLU(),
    nn.Conv2d(20,64,5),
    nn.ReLU()
)
# Sequential: layer 모음집. 중간에 변형 시킬 수가 없음 class 화 되어있는 건 아님 class화 시키면 flatten 등 다른 연산 가능
# e.g.)첫 레이어 통과 후 fully connected layer 같은걸 적용 시킬 수 없음
# channel size 20 kernel 5
# channel size 20 -> 64, kernel 5 
# 5 kernel -> convolution -> 4만큼 줄어서 32 -> 28

value = torch.zeros((5,1,32,32)) # 입력 값
# 32가 입력으로 들어가면서 kernel 5*5
# 첫 레이어(Conv2d(1,20,5)): 1*32*32 -> 20*28*28
# 두번째 레이어(Conv2d(20,64,5)): 64*24*24
# classification 하려면 두번째 레이어를 flatten -> fully connected layer-> (softmax, sigmoid) -> output이 2개나오도록(2진분류)
 

out = minsu(value) # 출력

print(value.shape)
print(out.shape)
print(minsu)


torch.Size([5, 1, 32, 32])
torch.Size([5, 64, 24, 24])
Sequential(
  (0): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU()
  (2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (3): ReLU()
)


: 